services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - API_URL=http://127.0.0.1:8000
    depends_on:
      - backend