version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    mem_limit: 450m
    cpus: '0.5'
    environment:
      - WEB_CONCURRENCY=1

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    mem_limit: 450m
    cpus: '0.5'

networks:
  default:
    driver: bridge